name: tokkoo_pos_lite
description: "Solusi aplikasi kasir simpel untuk toko Anda"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  slang: ^4.4.1

  cupertino_icons: ^1.0.6

  # State Manager
  provider: ^6.1.2

  # Necessary
  intl: ^0.19.0
  http: ^1.2.1

  # Offline DB
  objectbox: ^2.5.1
  objectbox_flutter_libs: ^2.5.1
  shared_preferences: ^2.2.2

  # ESC Printer
  permission_handler: ^11.3.1
  flutter_esc_pos_utils: ^1.0.1
  print_bluetooth_thermal: ^1.1.5

  # UI - Utils
  multi_select_flutter: ^4.1.3
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0

  # Info
  package_info_plus: ^6.0.0
  device_info_plus: ^10.0.1
  path_provider: ^2.1.2

  # Utils
  url_launcher: ^6.3.1
  app_settings: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  objectbox_generator: ^2.5.1
  build_runner: ^2.4.9

dependency_overrides:
  win32: ^5.5.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          style: italic
          weight: 900
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Regular.ttf
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-BoldItalic.ttf
          style: italic
          weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Monteserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Monteserrat/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Monteserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Monteserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Monteserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Monteserrat/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Monteserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Monteserrat/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Monteserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Monteserrat/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Monteserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Monteserrat/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Monteserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Monteserrat/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
